using System.Collections.Generic;
using Escape.Data;
using UnityEngine;

namespace Escape.Core
{
    /// <summary>
    /// Indexes every design-time definition asset by Id. Definitions are
    /// loaded from Resources/Definitions (generated by the web importer or
    /// authored by hand). Runtime code resolves string ids through here so
    /// unknown ids fail safely instead of poisoning state.
    /// </summary>
    public interface IContentDatabase
    {
        StealthTuning Tuning { get; }
        IReadOnlyCollection<EvidenceDefinition> Evidence { get; }
        IReadOnlyCollection<ObjectiveDefinition> Objectives { get; }
        IReadOnlyCollection<TerminalDefinition> Terminals { get; }
        IReadOnlyCollection<EndingDefinition> Endings { get; }
        IReadOnlyCollection<InsightDefinition> Insights { get; }
        IReadOnlyCollection<DocumentDefinition> Documents { get; }
        bool TryGetEvidence(string id, out EvidenceDefinition def);
        bool TryGetObjective(string id, out ObjectiveDefinition def);
        bool TryGetTerminal(string id, out TerminalDefinition def);
        bool TryGetEnding(string id, out EndingDefinition def);
        bool TryGetInsight(string id, out InsightDefinition def);
        bool TryGetDocument(string id, out DocumentDefinition def);
        bool IsKnownScene(string sceneId);
        string SceneName(string sceneId);
    }

    public sealed class ContentDatabase : IContentDatabase
    {
        private readonly Dictionary<string, EvidenceDefinition> _evidence = new Dictionary<string, EvidenceDefinition>();
        private readonly Dictionary<string, ObjectiveDefinition> _objectives = new Dictionary<string, ObjectiveDefinition>();
        private readonly Dictionary<string, TerminalDefinition> _terminals = new Dictionary<string, TerminalDefinition>();
        private readonly Dictionary<string, EndingDefinition> _endings = new Dictionary<string, EndingDefinition>();
        private readonly Dictionary<string, InsightDefinition> _insights = new Dictionary<string, InsightDefinition>();
        private readonly Dictionary<string, DocumentDefinition> _documents = new Dictionary<string, DocumentDefinition>();
        private readonly Dictionary<string, string> _sceneNames = new Dictionary<string, string>
        {
            { SceneId.Bootstrap, "Bootstrap" },
            { SceneId.MainMenu, "MainMenu" },
            { SceneId.Dock, "Dock" },
            { SceneId.ServiceEntrance, "ServiceEntrance" },
            { SceneId.MansionOffice, "MansionOffice" },
            { SceneId.SecurityWing, "SecurityWing" },
            { SceneId.BunkerServerRoom, "BunkerServerRoom" },
            { SceneId.BroadcastTower, "BroadcastTower" },
        };

        public StealthTuning Tuning { get; private set; }
        public IReadOnlyCollection<EvidenceDefinition> Evidence => _evidence.Values;
        public IReadOnlyCollection<ObjectiveDefinition> Objectives => _objectives.Values;
        public IReadOnlyCollection<TerminalDefinition> Terminals => _terminals.Values;
        public IReadOnlyCollection<EndingDefinition> Endings => _endings.Values;
        public IReadOnlyCollection<InsightDefinition> Insights => _insights.Values;
        public IReadOnlyCollection<DocumentDefinition> Documents => _documents.Values;

        public static ContentDatabase Load()
        {
            var db = new ContentDatabase();
            foreach (var e in Resources.LoadAll<EvidenceDefinition>("Definitions")) db._evidence[e.Id] = e;
            foreach (var o in Resources.LoadAll<ObjectiveDefinition>("Definitions")) db._objectives[o.Id] = o;
            foreach (var t in Resources.LoadAll<TerminalDefinition>("Definitions")) db._terminals[t.Id] = t;
            foreach (var e in Resources.LoadAll<EndingDefinition>("Definitions")) db._endings[e.Id] = e;
            foreach (var i in Resources.LoadAll<InsightDefinition>("Definitions")) db._insights[i.Id] = i;
            foreach (var d in Resources.LoadAll<DocumentDefinition>("Definitions")) db._documents[d.Id] = d;
            db.Tuning = Resources.Load<StealthTuning>("Definitions/StealthTuning");
            if (db.Tuning == null)
            {
                Debug.LogWarning("[ContentDatabase] No StealthTuning asset found; using runtime defaults.");
                db.Tuning = ScriptableObject.CreateInstance<StealthTuning>();
            }
            return db;
        }

        public bool TryGetEvidence(string id, out EvidenceDefinition def) => _evidence.TryGetValue(id ?? "", out def);
        public bool TryGetObjective(string id, out ObjectiveDefinition def) => _objectives.TryGetValue(id ?? "", out def);
        public bool TryGetTerminal(string id, out TerminalDefinition def) => _terminals.TryGetValue(id ?? "", out def);
        public bool TryGetEnding(string id, out EndingDefinition def) => _endings.TryGetValue(id ?? "", out def);
        public bool TryGetInsight(string id, out InsightDefinition def) => _insights.TryGetValue(id ?? "", out def);
        public bool TryGetDocument(string id, out DocumentDefinition def) => _documents.TryGetValue(id ?? "", out def);
        public bool IsKnownScene(string sceneId) => _sceneNames.ContainsKey(sceneId ?? "");
        public string SceneName(string sceneId) => _sceneNames.TryGetValue(sceneId ?? "", out var n) ? n : null;
    }
}
